use_frameworks!

platform :ios, '9.0'

target 'WXNetworkingSwift_Example' do
  pod 'WXNetworkingSwift', :path => '../'

  target 'WXNetworkingSwift_Tests' do
    inherit! :search_paths

    
  end
end
